# Generated by Django 4.0.1 on 2022-03-13 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeBoxSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BoxTitle', models.CharField(max_length=255)),
                ('BoxDescription', models.TextField()),
                ('BoxIcons', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productivityImage', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
                ('productivityHeading', models.CharField(max_length=255)),
                ('productivityDescription', models.TextField()),
                ('productivityTestimonial', models.CharField(max_length=255)),
                ('writterImage', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
                ('writterBy', models.CharField(max_length=255)),
                ('productHeadingTwo', models.CharField(max_length=255, null=True)),
                ('productDescriptionTwo', models.TextField(null=True)),
                ('productTestimonialTwo', models.CharField(max_length=255, null=True)),
                ('ProductImageTwo', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
                ('writter_by', models.CharField(max_length=255, null=True)),
                ('writterImageTwo', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writer_image', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
                ('writer_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('video_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HomeInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterfaceHeading', models.CharField(max_length=255)),
                ('InterfaceDescription', models.TextField()),
                ('InterfaceBannerImage', models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/')),
                ('titleOne', models.CharField(max_length=255)),
                ('headingOne', models.CharField(max_length=255)),
                ('titleTwo', models.CharField(max_length=255)),
                ('headingtwo', models.CharField(max_length=255)),
                ('TitleThree', models.CharField(max_length=255)),
                ('headingthree', models.CharField(max_length=255)),
                ('titleFour', models.CharField(max_length=255)),
                ('headingfour', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
