# Generated by Django 4.0.1 on 2022-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.CharField(help_text='This is the grey text', max_length=100),
        ),
    ]
