# Generated by Django 4.0.1 on 2022-03-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometestimonial',
            name='writer_image',
        ),
    ]
