# Generated by Django 4.0.1 on 2022-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(),
        ),
    ]
