# Generated by Django 4.0.1 on 2022-02-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_home_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='HomeBanner',
        ),
    ]
