# Generated by Django 4.0.1 on 2022-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_home_homebanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='BannerImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
