# Generated by Django 4.0.1 on 2022-03-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_bannerimage_homebanner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
