# Generated by Django 4.0.1 on 2022-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homebanner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homebanner',
            name='image',
        ),
        migrations.AddField(
            model_name='homebanner',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail/%Y/%m/%d/'),
        ),
    ]
